version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}
    blackbox_data: {}
    alertmanager: {}

services:

  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    restart: unless-stopped
    ports:
     - "9090:9090"

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    restart: unless-stopped
    volumes:
      - ./blackbox:/config
    command: --config.file=/config/blackbox.yml
    ports:
      - "9115:9115"

  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: unless-stopped
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:10.0.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    ports:
       - "3000:3000"

