global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'docker-host-alpha'

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

# Node-Экспортер prometheus
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx_example]  # Смотрит на HTTP 200 отклик.
    static_configs:
      - targets:

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
